INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('2.4mR', '2.4mR - Foque', 'JDF1', 'ARG', 6);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('2.4mR', '2.4mR - Mayor', 'MF15', 'ARG', 0);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('29ER', '29ER - HK 8477 - Funda Cubierta', 'HK8477-FCUB', 'ARG', 2);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('420', '*420 - Foque J12', 'J12/B', 'BRA', 61);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('420', '*420 - Foque J13', 'J13', 'ARG', 11);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('420', '*420 - Mayor M11', 'M11', 'ARG', 8);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('420', '*420 - Mayor M7', 'M7', 'ARG', 6);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('420', '*420 - Mayor M9', 'M9', 'ARG', 51);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('420', '*420 - Spi S1', null, 'ARG', 0);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('420', '*420 - Spi S5', 'S05-BL/R:018994', 'ARG', 4);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('420', '420 - HK 8041 - Funda Cubierta S', null, 'ARG', 0);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('420', '420 - HK 8043 - Funda Timon', 'HK8043-FTIM', 'ARG', 2);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('470', 'JIB S5 B4', 'JIB S5 B4', 'BRA', 0);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('BOLSAS', 'CAJON #4 (LOTE 2 UN.)', 'ZSSL #4 x2', 'ARG', 0);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('BOLSAS', 'CAJON #5 (LOTE 2 UN.)', 'ZSML-5 x 6 UNIDADES', 'ARG', 0);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('BOLSAS', 'CAJON #6 (LOTE 2 UN.)', 'ZSML #5 X2', 'ARG', 0);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('BOLSAS', 'CAJON #7 (LOTE 2 UN.)', 'ZSXLL #7 x2', 'ARG', 0);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('BOLSAS', 'TORTUGA #10 (LOTE 6 UN.)', 'ZZJ10L x 6 UNIDADES', 'ARG', 0);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('BOLSAS', 'TORTUGA #12 (LOTE 6 UN.)', 'ZZJ12L X 12', 'ARG', 0);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('BOLSAS', 'TORTUGA #14 (LOTE 6 UN.)', 'ZZJ14L X 6', 'ARG', 0);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('CADET', '*CADET - Foque J1-S', 'J1S', 'ARG', 38);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('CADET', '*CADET - Mayor I-3', 'MI3', 'ARG', 22);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('CADET', '*CADET - Spi CS-3', 'CS3', 'ARG', 30);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('CADET', 'CADET - Foque J1-V3', null, 'ARG', 0);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('CADET', 'CADET - Foque J1-V3 Plus', '-27 J CADET DISC.', 'ARG', 37);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('CADET', 'CADET - Mayor M-1', 'MIV5', 'ARG', 38);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('CORUM 27', 'CORUM 27 - Asy A2 clase 2014 V1', 'ASY A2.V1', 'ARG', 13);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('CORUM 27', 'CORUM 27 - Asy A2 Runner', null, 'ARG', 0);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('CORUM 27', 'CORUM 27 - Genoa G-12', 'G12', 'ARG', 6);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('CORUM 27', 'CORUM 27 - My M12', null, 'ARG', 0);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('CORUM 27', 'CORUM 27 - SPI S2', null, 'ARG', 0);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('CORUM 27', 'CORUM 27 -Foque J1', null, 'ARG', 0);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('DINGUE', 'M1', null, 'BRA', 0);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('F-18', 'F-18 - Asy AV2', 'NS SL', 'ARG', 0);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('F-18', 'F-18 - Foque JV9', 'FQ SHOCKWAVE LJ6', 'ARG', 0);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('F-18', 'F-18 - Mayor MHC1', 'MY DISEÃ‘O A DEF', 'ARG', 0);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('FINN', 'FINN - Mayor C2.1K', null, 'ARG', 0);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('FINN', 'FINN - Mayor MB1', 'MB1K', 'ARG', 0);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('FINN', 'FINN - Mayor MB1H', null, 'ARG', 0);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('FINN', 'FINN - Mayor MB2', null, 'ARG', 0);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('GRUMETE', '* GRUMETE NUEVO MOD - MY M12', 'M12-18 P/MAD', 'ARG', 0);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('GRUMETE', '*GRUMETE - Genoa G12', 'G12', 'ARG', 29);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('GRUMETE', '*GRUMETE - Spi S-12', 'S12', 'ARG', 11);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('GRUMETE', 'GRUMETE - Foque J1', 'J1-04 V1', 'ARG', 2018);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('GRUMETE', 'GRUMETE - Mayor M12', 'M12-20 M-ALUM', 'ARG', 18);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('HARBOR 20', 'HARBOR 20 - Foque J1 Kevlar AP', 'JCD1', 'ARG', 3);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('HARBOR 20', 'HARBOR 20 - Mayor MK-1 Kevlar AP', null, 'ARG', 0);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('HOLDER', 'HPE25 - MESTRA', null, 'ARG', 0);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('HPE 25', 'A2', null, 'BRA', 0);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('HPE 25', 'HPE25 - FOQUE JK5', null, 'BRA', 0);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('HPE 25', 'HPE25 - FOQUE JK6', 'Foque', 'BRA', 0);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('HPE 25', 'HPE25 - MESTRA MK5', null, 'BRA', 0);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('J-24 ESPECIALES', '*J-24 - Foque J1 ES', 'J1ES', 'ARG', 60);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('J-24 ESPECIALES', '*J-24 - Foque J1-ES+', 'MODELO A CONFIRMAR', 'ARG', 2);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('J-24 ESPECIALES', 'J-24 -  SPI Panam', 'SPAN V2', 'ARG', 4);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('J-24 ESPECIALES', 'J-24 - Foque J1Panam', 'JPAN', 'ARG', 22);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('J-24 ESPECIALES', 'J-24 - Mayor AP-1ES', null, 'ARG', 0);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('J-24 NEWPORT', '*J-24 -  Genoa NW DX7TT', 'H26173', 'ARG', 42);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('J-24 NEWPORT', '*J-24 - Mayor NW Fat Head', 'MNW', 'ARG', 46);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('J-24 NEWPORT', '*J-24 - Spi NW SN', null, 'ARG', 0);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('J-24 SAN DIEGO', '*J-24  - Spi FR-3', null, 'ARG', 0);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('J-24 SAN DIEGO', '*J-24 - Foque Super R.Blade', 'JSRB', 'ARG', 22);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('J-24 SAN DIEGO', '*J-24 - Genoa GP-7TW', null, 'ARG', 0);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('J-24 SAN DIEGO', '*J-24 - Mayor AP2', null, 'ARG', 0);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('J-24 SAN DIEGO', '*J-24 - Spi FR-2', 'SSD-FR2', 'ARG', 69);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('J-24 SPORT', '*J24  SPORT - Foque', 'JSPT', 'ARG', 2);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('J-24 SPORT', '*J24 SPORT - Genoa', 'GNW', 'ARG', 35);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('J-24 SPORT', '*J24 SPORT - Mayor', 'MSPT', 'ARG', 6);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('J-24 SPORT', '*J24 SPORT - Spi', null, 'ARG', 0);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('J-70', '*J-70 - Asy AP1', 'AAP1', 'ARG', 46);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('J-70', '*J-70 - Cajon Spi', 'C SP1', 'ARG', 8);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('J-70', '*J-70 - Foque J2HC', 'J2HC', 'ARG', 24);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('J-70', '*J-70 - Foque J6', 'J6', 'ARG', 33);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('J-70', '*J-70 - HK 8666 - FCUB/TRAVEL MO', 'HK8666 FCUB', 'ARG', 11);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('J-70', '*J-70 - HK 8667 - LSHEET BAG', 'HK8667-LSHEET BAG', 'ARG', 4);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('J-70', '*J-70 - HK 8669 - CESC/COMPANION', 'HK8669-CESC', 'ARG', 14);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('J-70', '*J-70 - HK 8670 - FTIM/RUDDER BA', 'HK8670-FTIM', 'ARG', 7);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('J-70', '*J-70 - HK 8671 - TILLERB', 'HK8671-TILLERB', 'ARG', 4);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('J-70', '*J-70 - HK 8673 - FFQ/UV SOCK', 'HK8673-CFQ', 'ARG', 10);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('J-70', '*J-70 - HK 8676 - SPEADER', 'HK8676-SPEADER', 'ARG', 4);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('J-70', '*J-70 - HK 8683 - ZIPMAST', 'HK8683-ZIPMAST', 'ARG', 2);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('J-70', '*J-70 - HK 8691 - HATCHBB', 'HK8691-HATCHBB', 'ARG', 4);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('J-70', '*J-70 - HK 8700 - FCUB-BOT/OVER', 'FCUBb', 'ARG', 2);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('J-70', '*J-70 - Mayor MF1', 'MF1', 'ARG', 10);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('J-70', '*J-70 - Mayor MXCS-1', 'MXCS2', 'ARG', 34);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('J-70', '*J-70 - Mayor MXCS-1 - NEW CLOTH', null, 'ARG', 0);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('J-70', '*J-70 - Mayor MXCS-2', 'MXCS2', 'ARG', 23);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('J-70', '*J-70 - Mayor MXCS-2 - NUEVA TEL', 'A CONFIRMAR MODELO', 'ARG', 0);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('J-70', '*J70 - Asy AMC1', 'AMC1', 'ARG', 11);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('J-70', 'J-70 - Foque J2R-4', 'J2R4', 'ARG', 12);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('LASER', 'ESTANDAR', null, 'BRA', 0);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('LASER', 'LASER - HK 8055 - Funda Cubierta', 'HK8055-FCUB', 'ARG', 3);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('LASER', 'RADIAL', null, 'BRA', 0);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('LIGHTNING', '*LIGHTNING - Foque J5A+', 'JV5+ ', 'ARG', 7);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('LIGHTNING', '*LIGHTNING - SR2', 'SR2', 'ARG', 3);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('LIGHTNING', 'LIGHTNING - Mayor M5', 'M5', 'ARG', 2);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('MASTRACCHIO DS-24', 'MASTRACCHIO DS-24 - Cubremayor G', null, 'ARG', 0);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('MASTRACCHIO DS-24', 'MASTRACCHIO DS-24 - Foque c/batt', 'J C/B', 'ARG', 10);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('MASTRACCHIO DS-24', 'MASTRACCHIO DS-24 - Foque p/e', 'J-P/E', 'ARG', 11);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('MASTRACCHIO DS-24', 'MASTRACCHIO DS-24 - Gennaker G1-', null, 'ARG', 0);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('MASTRACCHIO DS-24', 'MASTRACCHIO DS-24 - Mayor 1 Rizo', 'M1R', 'ARG', 10);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('MASTRACCHIO DS-24', 'MASTRACCHIO DS-24 - Mayor 2 Rizo', 'M2R', 'ARG', 7);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('MATCH 30', 'MATCH 30 - Asy A2', 'A2', 'ARG', 14);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('MATCH 30', 'MATCH 30 - Genoa AP', 'GAP', 'ARG', 11);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('MATCH 30', 'MATCH 30 - Genoa G#1 AP/CS', null, 'ARG', 0);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('MATCH 30', 'MATCH 30 - Genoa G#C1  Light/Med', null, 'ARG', 0);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('MATCH 30', 'MATCH 30 - Genoa G#C2  Med./Hvy', 'G# MED HVY', 'ARG', 0);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('MATCH 30', 'MATCH 30 - Mayor M1 SQ Head', 'M1', 'ARG', 7);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('MICRO VOLKER', 'M VOLKER - Foque JDC1', 'FOQUE DC1 CRUCERO', 'ARG', 3);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('MICRO VOLKER', 'M VOLKER - Foque JP1', 'JP1', 'ARG', 2);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('MICRO VOLKER', 'M VOLKER - My MDC1', 'MAYOR DC1 CRUCERO', 'ARG', 2);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('MICRO VOLKER', 'M VOLKER - My MP1', 'MP1', 'ARG', 2);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('NACRA20', 'Mestra', null, 'BRA', 0);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('OPEN 590', 'OPEN 590 - A1', null, 'BRA', 0);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('OPEN 590', 'OPEN 590 - Buja P1', null, 'BRA', 0);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('OPEN 590', 'OPEN 590 - Mayor P1', null, 'BRA', 0);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('OPTIMIST', '*OPT - HK8111- FDA CASCO', 'HK-8111C', 'ARG', 4);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('OPTIMIST', '*OPT - Mayor CLUB', 'MCLUB', 'BRA', 97);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('OPTIMIST', '*OPT - Mayor NR1', 'MNR1', 'ARG', 8);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('OPTIMIST', '*OPT - Mayor NR2', 'MNR2', 'ARG', 9);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('OPTIMIST', '*OPT - MAYOR NR3', 'MNR3', 'ARG', 10);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('OPTIMIST', '*OPT - Mayor R1', 'MNR1', 'ARG', 5);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('OPTIMIST', '*OPT - Mayor R2', 'MR2', 'ARG', 22);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('OPTIMIST', '*OPT - Mayor R4', 'MR4', 'ARG', 30);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('OPTIMIST', '*OPT - Mayor R5', 'MR5', 'ARG', 50);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('OPTIMIST', '*OPT - Mayor ZX4', 'MZX4', 'ARG', 36);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('OPTIMIST', '*OPT - Mayor ZX5', 'MZX5', 'ARG', 36);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('OPTIMIST', 'OPT - Mayor CZ5', 'M CZ5', 'ARG', 7);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('OPTIMIST', 'OPT - Mayor DZ6', null, 'ARG', 0);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('OPTIMIST', 'OPT - Mayor MCO', null, 'ARG', 0);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('OPTIMIST', 'OPT - Mayor V4', 'V4', 'ARG', 23);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('OPTIMIST', 'OPT - Mayor V6', 'V6', 'ARG', 72);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('OPTIMIST', 'OPT - Mayor XL08', 'L08', 'ARG', 0);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('OPTIMIST RV+', 'OPT RV+ - Mayor', null, 'ARG', 0);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('PAMPERO', '*PAMPERO - Foque CD1', null, 'ARG', 0);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('PAMPERO', '*PAMPERO - Foque D12 HTP', 'JD12', 'ARG', 93);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('PAMPERO', '*PAMPERO - Mayor CD1', null, 'ARG', 0);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('PAMPERO', '*PAMPERO - Mayor D12 HTP', 'MD12', 'ARG', 89);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('PIRATA', 'PIRATA - Mayor CM4', null, 'ARG', 0);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('SNIPE', '*SNIPE - Foque R3LM GR', 'JR3LM', 'ARG', 45);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('SNIPE', '*SNIPE - Mayor SW3', 'MSW3', 'ARG', 50);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('SNIPE', '*SNIPE - Mayor SW4', 'MSW4', 'ARG', 80);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('SNIPE', 'Mestra SW3', null, 'BRA', 0);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('SNIPE', 'Mestra SW4', null, 'BRA', 0);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('SNIPE', 'PR3', null, 'BRA', 0);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('SNIPE', 'SNIPE - Foque BR1DH', 'FQ BR1', 'ARG', 0);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('SNIPE', 'SNIPE - Foque R3LM', 'JR3LM', 'BRA', 390);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('SNIPE', 'SNIPE - Funda Casco HK-8252', 'FCAS', 'ARG', 9);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('SNIPE', 'SNIPE - Funda Mastil x 3u', null, 'ARG', 0);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('SNIPE', 'SNIPE - Funda Orza', 'SNIPE-FORZ', 'ARG', 9);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('SNIPE', 'SNIPE - Funda Timon', 'SNIPE-FTIM', 'ARG', 9);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('SNIPE', 'Snipe - HK 8251 - FCUBSOFT', 'HK8251', 'ARG', 5);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('SNIPE', 'SNIPE - HK 8251 - FCUBSU', null, 'ARG', 0);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('SNIPE', 'SNIPE - Mayor AP5', 'MAP5', 'ARG', 18);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('SNIPE', 'SNIPE - Mayor CB2', '53 - SNIPE MCB2', 'ARG', 23);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('SNIPE', 'SNIPE - Mayor M-12', null, 'ARG', 0);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('SNIPE', 'SNIPE - Mayor M6X', 'M6X', 'ARG', 96);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('SNIPE', 'SNIPE - Mayor PR3', 'MPR3', 'ARG', 41);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('SNIPE', 'SNIPE - Mayor SW4 con 130HTP', null, 'BRA', 0);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('SOLING', 'SOLING - Foque V1+', 'JV1+', 'ARG', 12);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('SOLING', 'SOLING - Foque V1T', 'JV1T', 'ARG', 6);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('SOLING', 'SOLING - Mayor AP2', 'MAP2', 'BRA', 6);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('SOLING', 'SOLING - Mayor AP2 -NUEVA TELA 2', 'MAP2', 'ARG', 8);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('SOLING', 'SOLING - Spi Monster', 'S MON- SL', 'ARG', 0);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('SOLING', 'SOLING -Spi PD4', 'SPD4', 'ARG', 8);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('SOTO 33', 'SOTO 33 - A1.5', null, 'ARG', 0);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('SOTO 33', 'SOTO 33 - A2', null, 'ARG', 0);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('STAR', '*STAR - Foque J-1F o J1', 'J115', 'ARG', 76);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('STAR', '*STAR - Foque J07', 'J07', 'ARG', 4);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('STAR', '*STAR - Foque J115', 'STAR J115', 'ARG', 86);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('STAR', '*STAR - Foque J115R 2019', 'J115R', 'ARG', 11);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('STAR', '*STAR - Foque J115R 2020', null, 'ARG', 0);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('STAR', '*STAR - Foque J2-FR', 'J2-FR', 'ARG', 2);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('STAR', '*STAR - Foque J25 V3/ J2R', null, 'ARG', 0);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('STAR', '*STAR - HK8522 - FCUB', 'HK8522 FCUB', 'ARG', 2);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('STAR', '*STAR - Mayor M-16 AP', 'MS18', 'ARG', 58);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('STAR', '*STAR - Mayor M05 2019', 'M05', 'ARG', 19);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('STAR', '*STAR - Mayor M25  2019', 'M25', 'ARG', 7);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('STAR', 'STAR - Foque J1-R', null, 'ARG', 0);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('STAR', 'STAR - Foque J115AP', 'H30721', 'ARG', 8);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('STAR', 'STAR - Foque J15 Hvy Cloth', null, 'ARG', 0);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('STAR', 'STAR - Foque J1R5 -HTP', 'J1R5-01 HTP', 'ARG', 0);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('STAR', 'STAR - Foque J1R5- RSQ', 'J1R5', 'ARG', 5);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('STAR', 'STAR - Foque J25', null, 'ARG', 0);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('STAR', 'STAR - Mayor M-05 V1', 'MO5-', 'ARG', 15);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('STAR', 'STAR - Mayor M-05 V2 Scheidt', null, 'ARG', 0);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('STAR', 'STAR - Mayor M-16 H', 'M16H', 'ARG', 57);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('STAR', 'STAR - Mayor M-16 V1 Lars', 'M16-58 VER TELAS C/TB', 'ARG', 0);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('STAR', 'STAR - Mayor M-16 V3 Scheidt', 'M16.V4', 'ARG', 52);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('STAR', 'STAR - Mayor M-16 V4 Hvy Cloth S', null, 'ARG', 0);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('STAR', 'STAR - Mayor M2.1', 'M2', 'ARG', 2);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('STAR', 'STAR NUEVO MOD. - Foque J1-R4', 'J1.R4', 'ARG', 2);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('STAR', 'STAR NUEVO MOD. - Mayor M0-5', null, 'ARG', 0);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('STAR', 'STAR NUEVO MOD. - Mayor M1-6 V1', 'M1-16.V1', 'ARG', 2);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('STAR', 'STAR NUEVO MOD. - Mayor M1-6 V2', 'M1-16.V2', 'ARG', 2);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('TP52', 'CAJON TP-52 130 (A1-1.5)', 'CAJON TP-52 130 (A1-3)', 'ARG', 0);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('TP52', 'CAJON TP-52 150 (A2-A4-A5)', 'CAJON TP-52 150 (A2PLUS-1)', 'ARG', 71);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('TP52', 'CAJON TP-52 180 (A3)', null, 'ARG', 0);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('TP52', 'TP52 - A1 2017', null, 'ARG', 0);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('TP52', 'TP52 - A125-A 2016', null, 'ARG', 0);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('TP52', 'TP52 - A15-2 2017', 'A1.5', 'ARG', 0);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('TP52', 'TP52 - A2-NYLON 2016', null, 'ARG', 0);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('TP52', 'TP52 - A2-POLY 2016', 'A2-2 2017', 'ARG', 0);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('TP52', 'TP52 - A4-1 2015', null, 'ARG', 0);
INSERT INTO onedesignmodels (boat, sail, model, country, nextSequence) VALUES ('TP52', 'TP52 - Spi Staysail SS-1 2015', 'SS', 'ARG', 0);
