delete from boats;

insert into boats values ('1', '420 JP');
insert into boats values ('2', '470');
insert into boats values ('3', 'A-CAT');
insert into boats values ('4', 'CADET');
insert into boats values ('5', 'CORUM 27');
insert into boats values ('6', 'CORUM 200');
insert into boats values ('7', 'DINGUE M1');
insert into boats values ('8', 'DINGUE M0');
insert into boats values ('9', 'D-ONE');
insert into boats values ('10', 'F18');
insert into boats values ('11', 'FINN M0');
insert into boats values ('12', 'FINN M1');
insert into boats values ('13', 'GP26');
insert into boats values ('14', 'GRUMETE (M7)');
insert into boats values ('15', 'HARBOR 20');
insert into boats values ('16', 'HPE 25');
insert into boats values ('17', 'J24 SAN DIEGO');
insert into boats values ('18', 'J24 NUEVO MODELO 26-09');
insert into boats values ('19', 'J24 SPORT');
insert into boats values ('20', 'J24 PANAMERICANO');
insert into boats values ('21', 'LIGHTNING');
insert into boats values ('22', 'MICRO 19');
insert into boats values ('23', 'MICRO PRIMEX REG');
insert into boats values ('24', 'MICRO PRIMEX CRUC');
insert into boats values ('25', 'MICRO VOLKER REG');
insert into boats values ('26', 'MICRO VOLKER CRUC');
insert into boats values ('27', 'OPEN 590');
insert into boats values ('28', 'OPTIMIST RV+');
insert into boats values ('29', 'PAMPERO CRUCERO');
insert into boats values ('30', 'PAMPERO REGATA');
insert into boats values ('31', 'SKIPPER 21');
insert into boats values ('32', 'SNIPE AP4');
insert into boats values ('33', 'SNIPE J1');
insert into boats values ('34', 'SNIPE AP5');
insert into boats values ('35', 'SNIPE SW3');
insert into boats values ('36', 'SNIPE PR3');
insert into boats values ('37', 'FQ R3LM');
insert into boats values ('38', 'SNIPE M6X');
insert into boats values ('39', 'SNIPE M12');
insert into boats values ('40', 'SOLING');
insert into boats values ('41', 'STAR Modelo 0');
insert into boats values ('42', 'STAR M1 AP');
insert into boats values ('43', 'STAR Modelo 2');
insert into boats values ('44', 'TANGA');


delete from onedesign;

insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('1', '420 JP', 'Mayor', '25', 12);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('2', '420 JP', 'Foque', '25', 5);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('3', '420 JP', 'Spi', '194', 14);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('4', '470', 'Mayor', '25', 14);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('5', '470', 'Foque', '25', 6);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('6', 'A-CAT', 'Mayor', '202', 16);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('7', 'A-CAT', 'Mayor', '201', 4);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('8', 'CADET', 'Mayor', '24', 8);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('9', 'CADET', 'Foque', '22', 2);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('10', 'CADET', 'Spi', '40', 6.5);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('11', 'CORUM 27', 'Mayor', '36', 17);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('12', 'CORUM 27', 'Mayor', '35', 14);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('13', 'CORUM 27', 'Foque', '36', 14);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('14', 'CORUM 27', 'Foque', '35', 6);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('15', 'CORUM 27', 'Genoa', '36', 14);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('16', 'CORUM 27', 'Genoa', '35', 13);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('17', 'CORUM 27', 'Spi', '56', 53);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('18', 'CORUM 200', 'Mayor', '35', 15);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('19', 'CORUM 200', 'Mayor', '34', 5);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('20', 'CORUM 200', 'Genoa', '35', 13);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('21', 'CORUM 200', 'Genoa', '34', 7);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('22', 'CONTE 200', 'Mayor', '35', 19);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('23', 'CONTE 200', 'Mayor', '34', 7);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('24', 'CONTE 200', 'Genoa', '35', 9);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('25', 'CONTE 200', 'Genoa', '34', 6);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('26', 'CONTE 200', 'Spi', '47', 25);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('27', 'DINGUE M1', 'Mayor', '24', 13);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('28', 'DINGUE M0', 'Mayor', '22', 13);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('29', 'D-ONE', 'Mayor', '34', 17);
-- insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('30', 'D-ONE', 'Mayor', '', ); -- ventana??
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('31', 'F18', 'Mayor', '141', 15);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('32', 'F18', 'Mayor', '139', 6);
-- insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('33', 'F18', 'Mayor', '', 3); --ventana??
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('34', 'F18', 'Foque', '138', 6);
-- insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('35', 'F18', 'Foque', '', 2); --ventana??
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('36', 'F18', 'Asy', '59', 27);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('37', 'FINN M0', 'Mayor', '33', 14);
-- insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('38', 'FINN M0', 'Mayor', '', 1); -- nsp 271 oly  no encontrado!
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('39', 'FINN M0', 'Mayor', '47', 4);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('40', 'FINN M1', 'Mayor', '65', 14);
-- insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('41', 'FINN M1', 'Mayor', '', 1); -- nsp 271 oly  no encontrado!
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('42', 'FINN M1', 'Mayor', '53', 4);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('43', 'GP26', 'Mayor', '29', 24);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('44', 'GP26', 'Mayor', '28', 12);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('45', 'GP26', 'Foque', '30', 15);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('46', 'GP26', 'Foque', '29', 4);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('47', 'GP26', 'Genoa', '29', 13);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('48', 'GP26', 'Genoa', '28', 11);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('49', 'GP26', 'Asy', '56', 55);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('50', 'GP26', 'Asy', '47', 16);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('51', 'GRUMETE (M7)', 'Mayor', '124', 15);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('52', 'GRUMETE (M7)', 'Mayor', '23', 16);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('53', 'GRUMETE (M7)', 'Foque', '1', 10);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('54', 'GRUMETE (M7)', 'Genoa', '26', 19);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('55', 'GRUMETE (M7)', 'Spi', '59', 30);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('56', 'HARBOR 20', 'Mayor', '29', 15);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('57', 'HARBOR 20', 'Mayor', '28', 6);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('58', 'HARBOR 20', 'Spi', '47', 34);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('59', 'HPE 25', 'Mayor', '29', 21);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('60', 'HPE 25', 'Mayor', '28', 5);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('61', 'HPE 25', 'Asy', '47', 70);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('62', 'HPE 25', 'Ot', '41', 55);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('63', 'HPE 25', 'Ot', '42', 15);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('64', 'J24 SAN DIEGO', 'Mayor', '23', 17);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('65', 'J24 SAN DIEGO', 'Mayor', '27', 2.4);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('66', 'J24 SAN DIEGO', 'Mayor', '21', 2.9);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('67', 'J24 SAN DIEGO', 'Foque', '27', 23);
-- insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('68', 'J24 SAN DIEGO', 'Foque', '', ); -- sin mts
-- insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('69', 'J24 SAN DIEGO', 'Foque', '', ); -- sin mts
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('70', 'J24 SAN DIEGO', 'Genoa', '142', 10.9);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('71', 'J24 SAN DIEGO', 'Genoa', '140', 6.6);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('72', 'J24 SAN DIEGO', 'Genoa', '137', 2.2);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('73', 'J24 SAN DIEGO', 'Genoa', '125', 5);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('74', 'J24 SAN DIEGO', 'Genoa', '126', 7);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('75', 'J24 SAN DIEGO', 'Genoa', '127', 11);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('76', 'J24 SAN DIEGO', 'Spi', '59', 52);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('77', 'J24 NUEVO MODELO 26-09', 'Mayor', '27', 11);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('78', 'J24 NUEVO MODELO 26-09', 'Mayor', '23', 13);
-- insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('79', 'J24 SPORT', 'Mayor', '', 15); -- 7.0 oz no encontrada!
-- insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('80', 'J24 SPORT', 'Foque', '', 13); -- 7.0 oz no encontrada! 
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('81', 'J24 SPORT', 'Genoa', '72', 20);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('82', 'J24 SPORT', 'Spi', '47', 46);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('83', 'J24 PANAMERICANO', 'Foque', '118', 16);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('84', 'LIGHTNING', 'Spi', '41', 27);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('85', 'MICRO 19', 'Mayor', '26', 19);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('86', 'MICRO 19', 'Foque', '26', 11);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('87', 'MICRO 19', 'Spi', '41', 23);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('88', 'MICRO PRIMEX REG', 'Mayor', '203', 13);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('89', 'MICRO PRIMEX REG', 'Mayor', '202', 5);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('90', 'MICRO PRIMEX REG', 'Foque', '202', 8);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('91', 'MICRO PRIMEX REG', 'Foque', '201', 4);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('92', 'MICRO PRIMEX CRUC', 'Mayor', '14', 16);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('93', 'MICRO PRIMEX CRUC', 'Foque', '13', 9);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('94', 'MICRO VOLKER REG', 'Mayor', '35', 11);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('95', 'MICRO VOLKER REG', 'Foque', '34', 12);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('96', 'MICRO VOLKER CRUC', 'Mayor', '14', 14);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('97', 'MICRO VOLKER CRUC', 'Spi', '56', 26);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('98', 'OPEN 590', 'Mayor', '139', 17);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('99', 'OPEN 590', 'Mayor', '138', 13);
-- insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('100', 'OPEN 590', 'Mayor', '', 4);  -- ventana
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('101', 'OPEN 590', 'Foque', '138', 13);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('102', 'OPEN 590', 'Asy', '47', 56);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('103', 'OPTIMIST RV+', 'Mayor', '22', 7);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('104', 'PAMPERO CRUCERO', 'Mayor', '13', 12);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('105', 'PAMPERO CRUCERO', 'Foque', '13', 6);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('106', 'PAMPERO REGATA', 'Mayor', '25', 12);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('107', 'PAMPERO REGATA', 'Foque', '25', 6);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('108', 'SKIPPER 21', 'Mayor', '35', 17);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('109', 'SKIPPER 21', 'Mayor', '34', 5);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('110', 'SKIPPER 21', 'Genoa', '35', 12);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('111', 'SKIPPER 21', 'Genoa', '34', 5);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('112', 'SNIPE AP4', 'Mayor', '24', 11);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('113', 'SNIPE AP4', 'Foque', '24', 6);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('114', 'SNIPE AP4', 'Genoa', '24', 3.3);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('115', 'SNIPE J1', 'Foque', '24', 8);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('116', 'SNIPE J1', 'Foque', '118', 0.5);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('117', 'SNIPE AP5', 'Mayor', '24', 11);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('118', 'SNIPE AP5', 'Mayor', '25', 5);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('119', 'SNIPE SW3', 'Mayor', '24', 11);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('120', 'SNIPE SW3', 'Mayor', '25', 4);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('121', 'SNIPE SW3', 'Foque', '24', 6);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('122', 'SNIPE SW3', 'Foque', '25', 2);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('123', 'SNIPE PR3', 'Mayor', '24', 11);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('124', 'SNIPE PR3', 'Foque', '24', 4);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('125', 'SNIPE PR3', 'Genoa', '24', 7);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('126', 'FQ R3LM', 'Mayor', '25', 4);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('127', 'FQ R3LM', 'Foque', '25', 3);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('128', 'SNIPE M6X', 'Mayor', '24', 8);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('129', 'SNIPE M6X', 'Mayor', '25', 5);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('130', 'SNIPE M12', 'Mayor', '18', 9);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('131', 'SNIPE M12', 'Mayor', '19', 5);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('132', 'SOLING', 'Mayor', '21', 10.6);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('133', 'SOLING', 'Mayor', '117', 10.8);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('134', 'SOLING', 'Foque', '118', 10.1);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('135', 'SOLING', 'Foque', '27', 1.6);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('136', 'SOLING', 'Genoa', '20', 6.65);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('137', 'SOLING', 'Genoa', '21', 4.9);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('138', 'SOLING', 'Spi', '59', 47.2);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('139', 'STAR Modelo 0', 'Mayor', '200', 39);  -- discontinuado
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('140', 'STAR Modelo 0', 'Mayor', '118', 2);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('141', 'STAR Modelo 0', 'Foque', '200', 10.5); -- discontinuado
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('142', 'STAR M1 AP', 'Mayor', '114', 19);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('143', 'STAR M1 AP', 'Mayor', '116', 4.1);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('144', 'STAR M1 AP', 'Mayor', '25', 11);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('145', 'STAR M1 AP', 'Mayor', '26', 4);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('146', 'STAR M1 AP', 'Mayor', '118', 1);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('147', 'STAR M1 AP', 'Foque', '19', 5.5);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('148', 'STAR M1 AP', 'Foque', '21', 4.5);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('149', 'STAR M1 AP', 'Foque', '118', 0.5);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('150', 'STAR Modelo 2', 'Mayor', '20', 22);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('151', 'STAR Modelo 2', 'Mayor', '26', 16);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('152', 'STAR Modelo 2', 'Foque', '20', 6);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('153', 'STAR Modelo 2', 'Foque', '21', 4.5);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('154', 'STAR Modelo 2', 'Foque', '118', 1);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('155', 'TANGA', 'Mayor', '26', 11);
insert into onedesign (id, boat, sailPrefix, clothId, mts) values ('156', 'TANGA', 'Genoa', '26', 5);

